# This file was generated by GoReleaser. DO NOT EDIT.
class Localroast < Formula
  desc "Localroast quickly stubs a HTTP server"
  homepage "https://github.com/caalberts/localroast"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/caalberts/localroast/releases/download/v0.4.0/localroast_0.4.0_Darwin_x86_64.tar.gz"
    sha256 "6e7dea5347ed76a4a137406b66eff3fcb6296485ccecaa22eb8fa9520083ec3b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/caalberts/localroast/releases/download/v0.4.0/localroast_0.4.0_Linux_x86_64.tar.gz"
      sha256 "3774f0c94b2539772673afff84805623d153ed837cb12e7412876259e4a29246"
    end
  end

  def install
    bin.install "localroast"
  end

  test do
    system "#{bin}/localroast version"
  end
end
